name: linter-check
run-name: Linter Check

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
    paths-ignore:
      - '**.md'

jobs:
  eslint-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Installing packages
        working-directory: ./
        run: yarn

      - name: Yarn fix
        working-directory: ./
        run: yarn fix
